### Definição de variáveis

@baseUrl = http://localhost:8080

###

GET {{baseUrl}}/
Accept: application/json

###

POST {{baseUrl}}/url
Content-Type: application/json
Accept: application/json

{
  "name": "google-two",
  "url": "https://www.google.com/"
}

###

GET {{baseUrl}}/url/22
Accept: application/json

###

PUT {{baseUrl}}/url/24d57fb1-3e22-4b07-9a4c-3de848cb0674
Content-Type: application/json
Accept: application/json

{
  "name": "google-redirect",
  "url": "https://www.google.com/"
}

###

GET {{baseUrl}}/url-page?page=1&size=9
Accept: application/json

###

GET {{baseUrl}}/url-redirect/tHxkD4

###
