### Definição de variáveis

@baseUrl = http://localhost:8080

###

GET {{baseUrl}}/
Accept: application/json

###

POST {{baseUrl}}/url
Content-Type: application/json
Accept: application/json

{
  "name": "google",
  "url": "https://www.google.com/"
}

###

GET {{baseUrl}}/url/7d29384f-15c3-4867-a543-b269d70394d8
Accept: application/json

###

PUT {{baseUrl}}/url/24d57fb1-3e22-4b07-9a4c-3de848cb0674
Content-Type: application/json
Accept: application/json

{
  "name": "google-redirect",
  "url": "https://www.google.com/"
}

###

GET {{baseUrl}}/url-page?page=1&size=9
Accept: application/json

###

GET {{baseUrl}}/url-redirect/uFYabC

###
